# Site settings
title: 汀汀涔涔
name: 汀汀涔涔
email: ttccmvp@gmail.com
location: Chengdu, Sichuang
github_url: https://github.com/imwr
weibo_url: https://weibo.com/imwr
description: 汀汀涔涔 TT-CC
url: http://tt-cc.cc

# About/contact
author:
  contact:
    github:    https://github.com/imwr
    weibo:     http://weibo.com/imwr
    email:     ttccmvp@gmail.com

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from
  - kramdown
  - jekyll-github-metadata

# Where things are
collections:
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/
  my_snippet:
    output: true
    permalink: /snippet/:name/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: tag
  -
    scope:
      path: ""
      type: my_snippet
    values:
      layout: post

# Navigation
navs:
  -
    href: /
    label: Home
  -
    href: /blog
    label: Blog
    sub:
      -
        href: /category/jquery-plugin/
        label: Jquery-Plugin
      -
        href: /category/web-app/
        label: Web-App
      -
        href: /category/web-game/
        label: Web-Game
  -
    href: /open-source
    label: Open-Source
  -
    href: /snippet
    label: Snippets
  -
    href: /category
    label: Categories
  -
    href: /tag
    label: Tags

# Pagination
permalink: /:categories/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# github metadata
repository: imwr/imwr.github.com

# kramdown
kramdown:
  input: GFM
  syntax_highlighter: true

# Sidebar to show popular repo
side_bar_repo_limit: 5
pattern_module: 7

# Disque
disque: tt-cc.disqus.com
# Google Analytics
google_tracking_id : 'UA-79713062-1'

# skills
skill_software_keywords: [Java, Python3, Objective C, MySQL, MongoDB, SSDB, Redis, Lua, Hive]
skill_j2ee_keywords: [SpringMvc, Struct, MyBatis, Velocity]
skill_web_keywords: [HTML, CSS, JS, JQuery, AngularJS, Boostrap, Ajax, Django, Nodejs]

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules]

#test
easydebug: false
github:
  public_repositories: